version: "3.1"
services:
  node_app:
    build: .
    ports:
      - 80:8000
    external_links:
      - "mongo"
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
    restart: unless-stopped