version: "3.1"
services:
  node_app:
    build: .
    ports:
      - 80:8000
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
    restart: unless-stopped
  postgres:
    container_name: postgres-container
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    volumes:
      - ./postgresDb:/var/lib/postgresql/data
    restart: unless-stopped
